# Generated by Django 4.2.6 on 2023-10-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendee_Name', models.CharField(max_length=255)),
                ('AttendeeEmail', models.EmailField(max_length=254)),
                ('AttendeePhone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.CharField(max_length=255)),
                ('Event_Duration', models.DurationField()),
                ('Event_Date', models.DateField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Capacity', models.PositiveIntegerField()),
                ('Venue_name', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tickettype', models.CharField(max_length=255)),
                ('RegistrationDate', models.DateTimeField(auto_now_add=True)),
                ('Attendee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.attendee')),
                ('Event_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='Venue_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.venue'),
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('Org_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.organiser')),
            ],
        ),
    ]
